apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: aeromaya
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-for-oracle
        image: busybox:latest
        command: ['sh', '-c', 'until nc -z oracle-service 1521; do echo waiting for oracle; sleep 10; done']
      containers:
      - name: backend
        image: erivas04/aeromaya-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: backend-config
        env:
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: oracle-secret
              key: app-user
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: oracle-secret
              key: app-user-password
        readinessProbe:
          httpGet:
            path: /api/aeropuertos
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 10
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /api/aeropuertos
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
