apiVersion: v1
kind: PersistentVolume
metadata:
  name: oracle-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/oracle
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: role
          operator: In
          values:
          - oracle
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-pvc
  namespace: aeromaya
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
